### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by nevrome** [xronos-ch/xronos.rails#2]
### Functionality issues

- [ ] Breadcrumb menu doesn't reach CRUD pages ([Issue](https://github.com/codeplant/simple-navigation/issues/220))
- [ ] Autocomplete for `references` filter does not work. Most likely because `references` is a reserved name in Postgres ([Question](https://stackoverflow.com/questions/57872799))
- [x] Forms broke again because of user_id
- [x] Missing env variable documentation in README 
- [x] Highchart export is broken for the sum calibration
- [x] Lasso selection is also very slow because it works with a POST request on data/index. This POST causes the Datatables data preparation in app/datatables/selected_measurement_datatable.rb to run, which runs again with the subsequent GET request. *Instance variable caching.*
- [x] The calibration plots need some love: I just copied them and removed everything that did not work on the spot
- [x] Only registered users can currently access the calibration plots
- [x] DataTable sorting does not work
- [x] Lasso selection is very slow and breaks with too many entries: Cookie overflow
- [x] The nested form branch `arch_objects -> site_phases -> sites` does still not work and I don't know why 
- [x] `species` model: missing distinction of plural form causes issues
- [x] Master input form for `arch_object` model: some nested input does not work
- [x] Master input form for `arch_object` model: should be more responsive
- [x] Only objects with complete information are currently found by the master query. Unfortunately problem is caused by the `join`, not by the `where` statement

### Database

- [ ] Fell phases context: Besides C14 dates also fell phases are a very important data category for the project. They deserve an own sophisticated view. 
- [x] References have to be linked to Fell phases
- [x] Captcha for user registration
- [x] Restrict user registration with some sort of barrier
- [x] More database imports + related problems
- [x] Respective `source database` (context data import) not documented yet. `source database` should be a model with: *name*, *url*, *citation*, *licence*. Citation link in main table.
- [x] Responsible `user` not documented yet at object creation
- [x] Datatable paging not working correctly
- [x] New solution for the distinction of dendro_* and c14_measurements: `actable` system is too complicated down the line. Everything in one table? `has_one` or `belongs_to` relation to models `dendro` and `c14`?
- [x] `references` are not implemented yet
- [x] `species` are too complicated and at the same time not flexible enough. One text field for everything is enough
- [x] `periods` and `typo..._units` and `eco..._units` not implemented yet 
- [x] `fell_phases` not implemented yet
- [x] `site_phases` model is missing
- [x] Data import

### Page content

- [x] About section
- [x] API section
- [x] Database documentation

#### Very important
- [x] Filter dialogue is incomplete
- [x] RESTful API and documentation
- [x] CSV Export
- [x] Manual data selection in main table
- [x] Sum calibration for multiple measurements
- [x] Download is not complete: Does not give back every column
- [x] Map should keep zoom level
- [x] Better map markers
- [x] Better map marker popups
- [x] Interactive input and editing form
- [x] Extended main windows set back at reload

#### Important
- [ ] More sophisticated input validations
- [ ] Nice show actions. The relevant sites should always be shown on the map.
- [ ] Meaningful Unit tests
- [ ] Calibration Cronjob or calibration at input
- [ ] Discussion: Storing calibrated date + std? Algorithm? Current solution is... simple.
- [ ] Elaborated user permission system

### Deployment

- [x] Correct configuration of production environment
- [x] Change to postgres in development environment to avoid incompatibilities
- [x] Finetuning of deployment workflow
- [x] Decide on deployment system (docker vs. rails without vm)
- [x] Prepare host system

### Publication

- [x] Name? Xronos?
- [x] Add logo (also as fav icon)
- [ ] Publication of v.1.0 in the [Journal of Open Source Software](https://joss.theoj.org/)

**Comment by MartinHinz** [comment]
Transferred as file to the orga repo
